//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace mr_Remote_Lib.com.inetis.ddv {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IskalnikSoap", Namespace="http://ddv.inetis.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(xmlZavezanec))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class Iskalnik : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback IsciOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Iskalnik() {
            this.Url = global::mr_Remote_Lib.Properties.Settings.Default.Spock_Drustva_com_inetis_ddv_Iskalnik;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event IsciCompletedEventHandler IsciCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ddv.inetis.com/Isci", RequestNamespace="http://ddv.inetis.com/", ResponseNamespace="http://ddv.inetis.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] Isci(string iskalni_niz) {
            object[] results = this.Invoke("Isci", new object[] {
                        iskalni_niz});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void IsciAsync(string iskalni_niz) {
            this.IsciAsync(iskalni_niz, null);
        }
        
        /// <remarks/>
        public void IsciAsync(string iskalni_niz, object userState) {
            if ((this.IsciOperationCompleted == null)) {
                this.IsciOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsciOperationCompleted);
            }
            this.InvokeAsync("Isci", new object[] {
                        iskalni_niz}, this.IsciOperationCompleted, userState);
        }
        
        private void OnIsciOperationCompleted(object arg) {
            if ((this.IsciCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsciCompleted(this, new IsciCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ddv.inetis.com/")]
    public partial class xmlTransakcijskiRacun {
        
        private string xmlTRRField;
        
        private char xmlVrstaRacunaField;
        
        private string xmlImeBankeField;
        
        private System.DateTime xmlDatumOdprtjaField;
        
        private System.DateTime xmlDatumZadnjeSpremembeField;
        
        private bool xmlZaprtField;
        
        private System.DateTime xmlDatumZaprtjaField;
        
        /// <remarks/>
        public string xmlTRR {
            get {
                return this.xmlTRRField;
            }
            set {
                this.xmlTRRField = value;
            }
        }
        
        /// <remarks/>
        public char xmlVrstaRacuna {
            get {
                return this.xmlVrstaRacunaField;
            }
            set {
                this.xmlVrstaRacunaField = value;
            }
        }
        
        /// <remarks/>
        public string xmlImeBanke {
            get {
                return this.xmlImeBankeField;
            }
            set {
                this.xmlImeBankeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime xmlDatumOdprtja {
            get {
                return this.xmlDatumOdprtjaField;
            }
            set {
                this.xmlDatumOdprtjaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime xmlDatumZadnjeSpremembe {
            get {
                return this.xmlDatumZadnjeSpremembeField;
            }
            set {
                this.xmlDatumZadnjeSpremembeField = value;
            }
        }
        
        /// <remarks/>
        public bool xmlZaprt {
            get {
                return this.xmlZaprtField;
            }
            set {
                this.xmlZaprtField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime xmlDatumZaprtja {
            get {
                return this.xmlDatumZaprtjaField;
            }
            set {
                this.xmlDatumZaprtjaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ddv.inetis.com/")]
    public partial class xmlZavezanec {
        
        private string xmlDavcnaStevilkaField;
        
        private string xmlMaticnaStevilkaField;
        
        private char xmlStatusField;
        
        private string xmlNazivField;
        
        private string xmlNaslovField;
        
        private bool xmlZavezanecZaDDVField;
        
        private bool xmlPlacnikDDVField;
        
        private System.Nullable<System.DateTime> xmlDatumRegistracijeField;
        
        private string xmlDejavnostField;
        
        private string xmlUradField;
        
        private xmlTransakcijskiRacun[] xmlTransakcijskiRacuniField;
        
        /// <remarks/>
        public string xmlDavcnaStevilka {
            get {
                return this.xmlDavcnaStevilkaField;
            }
            set {
                this.xmlDavcnaStevilkaField = value;
            }
        }
        
        /// <remarks/>
        public string xmlMaticnaStevilka {
            get {
                return this.xmlMaticnaStevilkaField;
            }
            set {
                this.xmlMaticnaStevilkaField = value;
            }
        }
        
        /// <remarks/>
        public char xmlStatus {
            get {
                return this.xmlStatusField;
            }
            set {
                this.xmlStatusField = value;
            }
        }
        
        /// <remarks/>
        public string xmlNaziv {
            get {
                return this.xmlNazivField;
            }
            set {
                this.xmlNazivField = value;
            }
        }
        
        /// <remarks/>
        public string xmlNaslov {
            get {
                return this.xmlNaslovField;
            }
            set {
                this.xmlNaslovField = value;
            }
        }
        
        /// <remarks/>
        public bool xmlZavezanecZaDDV {
            get {
                return this.xmlZavezanecZaDDVField;
            }
            set {
                this.xmlZavezanecZaDDVField = value;
            }
        }
        
        /// <remarks/>
        public bool xmlPlacnikDDV {
            get {
                return this.xmlPlacnikDDVField;
            }
            set {
                this.xmlPlacnikDDVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> xmlDatumRegistracije {
            get {
                return this.xmlDatumRegistracijeField;
            }
            set {
                this.xmlDatumRegistracijeField = value;
            }
        }
        
        /// <remarks/>
        public string xmlDejavnost {
            get {
                return this.xmlDejavnostField;
            }
            set {
                this.xmlDejavnostField = value;
            }
        }
        
        /// <remarks/>
        public string xmlUrad {
            get {
                return this.xmlUradField;
            }
            set {
                this.xmlUradField = value;
            }
        }
        
        /// <remarks/>
        public xmlTransakcijskiRacun[] xmlTransakcijskiRacuni {
            get {
                return this.xmlTransakcijskiRacuniField;
            }
            set {
                this.xmlTransakcijskiRacuniField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void IsciCompletedEventHandler(object sender, IsciCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsciCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsciCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591